version: '3.8'
services:
    backend:
        build:
            context: ../anthonyhai-be-official
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 3301:3301
        expose:
            - 3301

    nginx:
        image: nginx:1.23.3
        ports:
            - 80:80
        volumes:
            - ./build:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
